/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::AssetImage MyBG0Image;
extern const Sifteo::AssetImage MyBG1Image;
extern const Sifteo::PinnedAssetImage MyRedSprite;
extern const Sifteo::PinnedAssetImage MyBlueSprite;
